version: '3'

services:
  frontend:
    container_name: litir-frontend
    image: litir-frontend:latest
    ports:
      - 8080:8080

  backend:
    container_name: litir-backend
    image: litir-backend:latest
    ports:
      - 5000:5000
    networks:
      - default
    environment: 
      # these are the environment variables that I am using inside psycop2 to make connection.
      - FLASK_APP=server.py
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres_password
      - POSTGRES_DATABASE=postgres

  postgres:
    container_name: postgres
    image: postgres:14.5
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres_password
      - POSTGRES_DB=postgres
    ports:
      - 5432:5432
    networks:
      - default